version: '3'
services:
  postgres:
    image: parrotstream/postgres:latest
    networks:
    - parrot
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    privileged: true
  zookeeper:
    image: parrotstream/zookeeper:latest
    ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888
    - 8080:8080
    networks:
    - parrot
  hadoop:
    image: parrotstream/hadoop:latest
    networks:
    - parrot
    external_links:
    - zookeeper
    volumes:
    - hadoop_conf:/etc/hadoop/conf
    ports:
    - 9870:9870
    - 9864:9864
    - 9820:9820
    - 8042:8042
    - 8088:8088
    - 8188:8188
    - 19888:19888
  hive:
    build:
      context: .
      dockerfile: Dockerfile
    image: parrotstream/hive:1.1.0-cdh5.11.1
    links:
    - hadoop
    - zookeeper
    - postgres
    networks:
    - parrot
    volumes:
    - hive_conf:/opt/hive/conf
    environment:
      PGPASSWORD: postgres
    ports:
    - 10000:10000
    - 10001:10001
    - 10002:10002
    - 10003:10003
    - 9083:9083
    - 50111:50111
    - 9999:9999
volumes:
  hadoop_conf: null
  hive_conf: null
networks:
  default:
    external:
      name: parrot
  parrot:
    driver: bridge
