version: "2"

services:

    postgres:
        image: postgres
        networks:
            - hadoop
        ports:
            - "15432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: postgres

networks:
    hadoop:
        driver: bridge

volumes:
    postgres_data:
